steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - appx-webapp-{{ENV}}
      - --platform=managed
      - --image=gcr.io/instabase-appx/webapp:{{WEBAPP_IMAGE_TAG}}
      - --region=us-west4
      - --allow-unauthenticated
      - --update-env-vars=[BACKEND_URL={{BACKEND_URL}}]
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - appx-backend-{{ENV}}
      - --platform=managed
      - --image=gcr.io/instabase-appx/backend:{{BACKEND_IMAGE_TAG}}
      - --region=us-west4
      - --allow-unauthenticated
      - --update-env-vars=[DB_URL={{DB_URL}}]
    waitFor: ["-"]
